### ISSUE TITLE
Add Contributing Guidelines

### ISSUE THREAD

**Issue by josephting** [josephting/manacher#4]
A very basic contributing guidelines is sufficient.

> Contributing

> When contributing to this repository, please first discuss the change you wish to make via issue, email, or any other method with the owners of this repository before making a change.

> [Link to a good how to create pull request guide]

**Comment by GledsonAfonso** [comment]
Can I get this?

**Comment by TheGoldenAurora** [comment]
Hi! I would be happy to help :)
