### ISSUE TITLE
Add PR welcome badge

### ISSUE THREAD

**Issue by josephting** [josephting/manacher#6]
Add ![](https://img.shields.io/badge/PRs-welcome-brightgreen) badge to README.md that links to http://makeapullrequest.com.

`https://img.shields.io/badge/PRs-welcome-brightgreen`

**Comment by manikkalai-kannan** [comment]
I will take this up

**Comment by manikkalai-kannan** [comment]
i will update

**Comment by josephting** [comment]
Closed with #14.
